### ISSUE TITLE
Can the codes compile in the VS 2012, Windows?

### ISSUE THREAD

**Issue by zjsprit** [taketwo/radical#1]
I currently try to compile the codes used by VS 2012 in Windows 8. When I used the CMake 3.7 to create the vs project files, I have the problems as follows ：

**CMake Error at CMakeLists.txt:22 (message):
  Cannot extract version number: The system cannot find the specified file。**

So can you give me some suggestions for solve the above problems?

**Comment by taketwo** [comment]
Hm, I have to admit I never tried to compile the project in Windows environment. I may look into fixing this when I have time.

In the meanwhile, as a quick fix you can try is to replace [lines 14-24 in CMakeLists](https://github.com/taketwo/radical/blob/master/CMakeLists.txt#L14-L24) with `set(PROJECT_VERSION "0.1")`.

**Comment by taketwo** [comment]
I've pushed a number of updates to the project in the recent months that add support for Windows platform. The library can be compiled and works fine on VS 2015. I don't have access to the earlier versions, but hope there will be no problems.
