### ISSUE TITLE
Can the codes run with Kinect v1 or Kinect v2 ?

### ISSUE THREAD

**Issue by gitliuyf** [taketwo/radical#10]
We only have Kinect RGBD cameras,  Can the codes run with Kinect v1 or Kinect v2 ? Thank you for suggestion!

**Comment by taketwo** [comment]
The OpenNI2 grabber is supposedly compatible with the first Kinect, however I have no idea if the hardware supports exposure time control (which is needed for response function calibration). Give it a try.

The second Kinect is definitely not supported.
