### ISSUE TITLE
compile issue -fdiagnostics-color

### ISSUE THREAD

**Issue by caselitz** [taketwo/radical#7]
When I try to compile radical on Ubuntu 14.04 with gcc 4.8.4 I get the error:
> c++: error: unrecognized command line option ‘-fdiagnostics-color’

Removing the flag from [here](https://github.com/taketwo/radical/blob/master/CMakeLists.txt#L50) helps.

Probably the gcc version is the problem, see [here](https://github.com/manio/vdr-plugin-dvbapi/issues/72#issuecomment-59515862). Not sure @taketwo if you want to keep it compatible with lower gcc versions...

**Comment by taketwo** [comment]
I added version checks to avoid this error. Thanks for reporting.
