### ISSUE TITLE
linker issue test_mean_image

### ISSUE THREAD

**Issue by caselitz** [taketwo/radical#8]
When I try to compile radical (Ubuntu 14.04, gcc 4.8.4) I get a linker error:

> [ 22%] Built target radical
[ 35%] Built target utils
[ 45%] Built target grabbers
[ 64%] Built target calibrate_radiometric_response
[ 74%] Built target calibrate_vignetting_response
[ 77%] Built target display_radiometric_response
[ 80%] Built target display_vignetting_response
[ 83%] Built target remove_vignetting
Linking CXX executable ../bin/test_mean_image
../src/utils/libutils.a(mean_image.cpp.o): In function `utils::MeanImage::addWeighted(cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&)':
mean_image.cpp:(.text+0x1ee1): undefined reference to `radical::Check::Check(std::string const&, cv::_InputArray const&)'
mean_image.cpp:(.text+0x1eec): undefined reference to `radical::Check::hasSize(cv::Size_<int>) const'
mean_image.cpp:(.text+0x1ef6): undefined reference to `radical::Check::hasType(int) const'
mean_image.cpp:(.text+0x20fa): undefined reference to `radical::Check::Check(std::string const&, cv::_InputArray const&)'
mean_image.cpp:(.text+0x2107): undefined reference to `radical::Check::hasChannels(int) const'
mean_image.cpp:(.text+0x2182): undefined reference to `radical::Check::Check(std::string const&, cv::_InputArray const&)'
mean_image.cpp:(.text+0x218d): undefined reference to `radical::Check::hasSize(cv::Size_<int>) const'
mean_image.cpp:(.text+0x219a): undefined reference to `radical::Check::hasType(int) const'
mean_image.cpp:(.text+0x2e23): undefined reference to `radical::Check::Check(std::string const&, cv::_InputArray const&)'
mean_image.cpp:(.text+0x2e36): undefined reference to `radical::Check::hasSize(cv::Size_<int>) const'
mean_image.cpp:(.text+0x2e41): undefined reference to `radical::Check::hasType(int) const'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/test_mean_image] Error 1
make[1]: *** [tests/CMakeFiles/test_mean_image.dir/all] Error 2
make: *** [all] Error 2

Am I doing something wrong?

**Comment by taketwo** [comment]
Thanks for the heads up, should be solved now. I also switched to using GCC on Travis as it seems to be more strict than Clang.
